In [1]:
import kagglehub

# Download latest version
path = kagglehub.model_download("google/movenet/tensorFlow2/singlepose-thunder")

print("Path to model files:", path)

100%|██████████| 5.95k/5.95k [00:00<00:00, 2.98MB/s]






100%|██████████| 10.4M/10.4M [00:00<00:00, 12.5MB/s]














100%|██████████| 24.2M/24.2M [00:02<00:00, 10.2MB/s]

Path to model files: C:\Users\assaf\.cache\kagglehub\models\google\movenet\tensorFlow2\singlepose-thunder\4


In [1]:
import tensorflow as tf
import cv2
import numpy as np

# Load MoveNet Thunder model
model = tf.saved_model.load("C:/Users/assaf/.cache/kagglehub/models/google/movenet/tensorFlow2/singlepose-thunder/4")
movenet = model.signatures['serving_default']

def preprocess_frame(frame):
    # Resize and normalize image
    img = tf.image.resize_with_pad(tf.expand_dims(frame, axis=0), 256, 256)
    img = tf.cast(img, dtype=tf.int32)
    return img

def draw_keypoints(frame, keypoints, confidence_threshold=0.3):
    h, w, _ = frame.shape
    for kp in keypoints[0, 0, :, :]:
        y, x, c = kp
        if c > confidence_threshold:
            cx, cy = int(x * w), int(y * h)
            cv2.circle(frame, (cx, cy), 4, (0, 255, 0), -1)

cap = cv2.VideoCapture(0)  # Or use 0 for webcam

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Convert to RGB and preprocess
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    input_image = preprocess_frame(rgb)

    # Run pose estimation
    outputs = movenet(input_image)
    keypoints = outputs['output_0'].numpy()

    print("Keypoints:", keypoints)
    # Draw keypoints
    draw_keypoints(frame, keypoints)

    # Show frame
    cv2.imshow('MoveNet Thunder', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

Keypoints: [[[[0.35282373 0.2964354  0.0465445 ]
   [0.34375936 0.2980706  0.03596657]
   [0.33408678 0.26864344 0.0242805 ]
   [0.36691478 0.2885952  0.07620681]
   [0.29975164 0.27537942 0.01731435]
   [0.3176684  0.37855056 0.04691218]
   [0.3181036  0.29924726 0.02861643]
   [0.40595138 0.44720864 0.10993389]
   [0.3569828  0.4011265  0.11384115]
   [0.42193073 0.4626309  0.24449842]
   [0.39304924 0.41418177 0.11863641]
   [0.45409817 0.4704626  0.21511695]
   [0.4925296  0.43227622 0.1089687 ]
   [0.63680863 0.6168015  0.07358122]
   [0.67021424 0.552961   0.08383578]
   [0.66280746 0.70108575 0.08682461]
   [0.71335125 0.5684972  0.076336  ]]]]
Keypoints: [[[[0.7022182  0.52306575 0.4822447 ]
   [0.6786087  0.5544129  0.5290564 ]
   [0.67059135 0.52550507 0.4941728 ]
   [0.6758445  0.63174146 0.2291    ]
   [0.6473759  0.5611577  0.29259378]
   [0.74895716 0.6256064  0.13919456]
   [0.6187278  0.5131355  0.21072961]
   [0.8228193  0.555744   0.0762826 ]
   [0.5946465  0.43902013